# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SADM
email: sbas.alec@gmail.com
description: > # this means to ignore newlines until "baseurl:"
# environment: production

baseurl: "" # the subpath of your site, e.g. /blog
url: "sebster3.github.io" # the base hostname & protocol for your site
twitter_username: sbas_alec
github_username:  Sebster3

# Build settings
permalink: /blog/:title
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  style: compressed

#Darkening Shim Variable - PNG, Base64 encoded
darkeningShim: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAABG2lUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNS41LjAiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIi8+CiA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+Gkqr6gAAAYJpQ0NQc1JHQiBJRUM2MTk2Ni0yLjEAACiRdZG/S0JRFMc/aVGUYVFDQ4OENWnYD6SWBqMsqAYzyGrRp08Dtcd7RkRr0CoURC39GuovqDVoDoKiCCJoay5qKXmdp4IReS7nns/93nsO954LtnBayRi1Pshkc3ooGHDNRxZc9S/YsNPKIM6oYmjTs+NhqtrnPTVWvPVataqf+9ea4glDgZoG4RFF03PCE8JTaznN4h3hdiUVjQufCXt0uaDwnaXHSvxqcbLE3xbr4dAo2FqEXclfHPvFSkrPCMvLcWfSq0r5PtZLHIns3KzELvFODEIECeBikjFG8dPHsMx+vPTTKyuq5PuK+TOsSK4is8Y6OsskSZHDI+qqVE9IVEVPyEizbvX/b18NdaC/VN0RgLpn03zvhvptKORN8+vINAvHYH+Cy2wlf+UQhj5Ez1c09wE4N+H8qqLFduFiCzoetageLUp2cZuqwtspNEeg7QYaF0s9K+9z8gDhDfmqa9jbhx4571z6AUyLZ9pe98JNAAAACXBIWXMAAAsTAAALEwEAmpwYAAAADUlEQVQImWNgYGCYAQAAnQCZFrgb8QAAAABJRU5ErkJggg==

host: 0.0.0.0

gems:
  -jekyll-sitemap
